### PR TITLE
Renamed the file 'syntax_test.py' to 'fixture.py'.

### PR DESCRIPTION
**Pull request by evandrocoan**
This is due the `Sublime Text` command to run all Unit Tests catch everything where its name starts within 'syntax_test' as a Syntax Unit Test. Them it will cause show invalid results as follows:

```
Packages/MarkdownLight/tests/syntax_test.py:1: unable to find SYNTAX TEST marker
FAILED: 1 of 22073 assertions in 42 files failed
[Finished]
```

image

### CODE REVIEW

**Comment by sekogan** [comment]
Thanks for the PR. I have few questions though:
1. How can I reproduce the issue? What command exactly should I run and where should I run it?
2. Why "new"? There is nothing new in these tests from my POV.

**Comment by evandrocoan** [comment]
I randomly choose new, it is just to not to start with `syntax_test`.
To reproduce it, just open a `Sublime Text's Syntax Test`, and go to `Tools -> Build With...` and choose `Syntax Test - All Syntaxes`.

multiselection_jumps

**Comment by sekogan** [comment]
It would be nice to have a meaningful file name. I suggest something like "fixture.py" instead of "new_syntax_test.py".

**Comment by evandrocoan** [comment]
@sekogan done.

**Comment by sekogan** [comment]
Thanks!

**Pull request merged**
